version: '3.9'
services:
  backend:
    image: ghcr.io/moo-hub/gplusapp-backend:latest
    container_name: backend
    env_file:
      - .env
    command: gunicorn -k uvicorn.workers.UvicornWorker gplus_smart_builder_pro.src.main:app --bind 0.0.0.0:8000 --workers 4
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always
    networks:
      - gplusnet

  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - gplusnet

  redis:
    image: redis:7
    container_name: redis
    env_file:
      - .env
    restart: always
    ports:
      - "6379:6379"
    networks:
      - gplusnet

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - gplusnet
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - gplusnet
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - gplusnet
    restart: always

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gplusnet
    restart: always

volumes:
  pgdata:

networks:
  gplusnet:
    driver: bridge
