version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: gplus_backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gplus_app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FRONTEND_URL=http://localhost:3000
    networks:
      - gplus-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gplus_frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api/v1
    networks:
      - gplus-network

  db:
    image: postgres:15
    container_name: gplus_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gplus_app
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gplus-network

  redis:
    image: redis:7
    container_name: gplus_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - gplus-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: gplus_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gplus.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - gplus-network

volumes:
  postgres-data:
  redis-data:

networks:
  gplus-network:
    driver: bridge