"""add_user_auth_fields

Revision ID: 82d0f66ad5d9
Revises: 79bd7ba369eb
Create Date: 2025-09-28 05:08:41.476049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82d0f66ad5d9'
down_revision: Union[str, Sequence[str], None] = '79bd7ba369eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pickup_requests', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('point_transactions', 'source',
               existing_type=postgresql.ENUM('PICKUP', 'REWARD', 'REFERRAL', 'SYSTEM', 'MANUAL', name='transactionsource'),
               nullable=True)
    op.alter_column('point_transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'CANCELLED', name='transactionstatus'),
               nullable=False)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'email_verified')
    op.alter_column('point_transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'CANCELLED', name='transactionstatus'),
               nullable=True)
    op.alter_column('point_transactions', 'source',
               existing_type=postgresql.ENUM('PICKUP', 'REWARD', 'REFERRAL', 'SYSTEM', 'MANUAL', name='transactionsource'),
               nullable=False)
    op.alter_column('pickup_requests', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
