name: Frontend Dispatch Driver

on:
  repository_dispatch:
    types: [frontend-ci-run]

jobs:
  run-frontend-on-ref:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target ref
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Test
        working-directory: frontend
        run: npm test --silent

      - name: Build
        working-directory: frontend
        run: npm run build --if-present
