name: Regenerate JS lockfile (Node 20)

on:
  workflow_dispatch:

jobs:
  regen-lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and regenerate lockfile
        run: |
          npm install --no-audit --no-fund

      - name: Commit and push updated lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package-lock.json frontend/package-lock.json || true
          if git diff --staged --quiet; then
            echo "No lockfile changes"
          else
            git commit -m "chore(frontend): regenerate package-lock.json on Node 20"
            git push origin HEAD:${{ github.ref_name }}
          fi
