name: repository-dispatch-driver
on:
  repository_dispatch:
    types: [run-ci-for-branch]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Parse payload
        id: payload
        run: |
          echo "BRANCH=${{ github.event.client_payload.ref }}" >> $GITHUB_OUTPUT
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.payload.outputs.BRANCH }}
          fetch-depth: 0
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd frontend || true
          npm ci
      - name: Run frontend tests
        run: |
          cd frontend || true
          npm test --if-present
      - name: Upload test results (optional)
        if: always()
        run: |
          echo "Driver finished for ${{ steps.payload.outputs.BRANCH }}" > driver-result.txt
          ls -la
