name: "Nightly Smoke E2E Tests"

# NOTE: This workflow runs gated "smoke" E2E tests that are intentionally
# heavier than the regular fast CI suite. The tests that exercise full
# end-to-end flows are guarded in the test code and only run when the
# environment variable RUN_E2E_SMOKE is set to 'true'.
#
# To run locally (POSIX):
#   RUN_E2E_SMOKE=true npx vitest run --config ./vitest.config.js --reporter json
# To run locally (PowerShell):
#   $env:RUN_E2E_SMOKE = 'true'; npx vitest run --config ./vitest.config.js --reporter json

on:
  schedule:
    - cron: '0 2 * * *' # Every day at 02:00 UTC (adjust as needed)
  workflow_dispatch: {}

jobs:
  smoke-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend deps
        run: |
          npm ci --prefix frontend

      - name: Run Vitest smoke E2E (gated)
        # Run Vitest from the repo root but use the frontend's node modules via --prefix
        # so the reporter output can be written reliably to the repo root as ./frontend-full-results.json
        run: |
          echo "Running gated E2E smoke tests..."
          npx --prefix frontend vitest run --config ./frontend/vitest.config.js --reporter json > ./frontend-full-results.json
        env:
          RUN_E2E_SMOKE: 'true'

      - name: Show JSON summary (first 200 lines)
        if: always()
        run: |
          echo '--- frontend-full-results.json (truncated) ---'
          head -n 200 ./frontend-full-results.json || true

      - name: Upload JSON results
        uses: actions/upload-artifact@v4
        with:
          name: frontend-smoke-json
          path: ./frontend-full-results.json
